run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gocritic
    - revive
    - staticcheck

linters-settings:
  errcheck:
    check-blank: false
    check-type-assertions: false
    exclude-functions:
      - (*bytes.Buffer).WriteByte
      - (*strings.Builder).WriteByte
  gocritic:
    enabled-checks:
      - appendAssign
      - badCall
      - badCond
      - dupArg
      - dupBranchBody
      - dupCase
      - dupSubExpr
      - offBy1
      - sloppyLen
      - truncateCmp
      - weakCond
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck
      - name: package-comments
      - name: var-naming
      - name: indent-error-flow
      - name: errorf
      - name: error-strings
      - name: range
      - name: superfluous-else
      - name: unreachable-code
      - name: redefines-builtin-id

issues:
  exclude-use-default: true
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: internal/gui/
      linters:
        - errcheck
        - gocritic
    - path: _test\.go
      linters:
        - errcheck
        - gocritic
